### ISSUE TITLE
How does docker machine deprecation effect this?

### ISSUE THREAD

**Issue by nomasprime** [Parallels/docker-machine-parallels#105]
Subscribed to Parallels specifically for this feature only to find the Docker feature it depends on is deprecated…ohhh Docker 🤦‍♂️ 

Will this repo be updated accordingly?

**Comment by legal90** [comment]
Hi @nomasprime 
Docker Machine project is deprecated (https://github.com/docker/machine/issues/4537), but should still be working at least on amd64-based computers (Apple machines with Intel CPU). Thus, this driver is expected to work there too.

I'm maintaining this driver on my spare time. Also, there are some developers from Parallels who try to help people here is this repo as they can. So, this project is not officially deprecated - as long as your computer is compatible with Docker Machine and Parallels Desktop for Mac, our driver should work there too.

Also, our driver is used in the project [`minikube`](https://github.com/kubernetes/minikube) as a library, so Docker Machine is not the only use case for our driver

**Comment by nomasprime** [comment]
Understood.

Thanks @legal90.
