### ISSUE TITLE
Docker machine cannot lookup docker.io

### ISSUE THREAD

**Issue by hombit** [Parallels/docker-machine-parallels#15]
Docker run and pull commands return host lookup error.

Output of `docker run ubuntu`:
```
Unable to find image 'ubuntu:latest' locally
Pulling repository docker.io/library/ubuntu
Get https://registry-1.docker.io/v1/repositories/library/ubuntu/tags/latest: dial tcp: lookup registry-1.docker.io: no such host
```

Output of `docker-machine env dockermachine`:
```
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://10.211.55.56:2376"
export DOCKER_CERT_PATH="/Users/hombit/.docker/machine/machines/dockermachine"
export DOCKER_MACHINE_NAME="dockermachine"
# Run this command to configure your shell:
# eval "$(docker-machine env dockermachine)"
```

OS X 10.11.1, Parallels Pro 11.0.2, Docker 1.9.0, docker-machine-parallels 1.0.1.

**Comment by legal90** [comment]
Duplicates #11 
Please, update Parallels Desktop to [11.1.0 (32202)](http://kb.parallels.com/en/123410)

**Comment by hombit** [comment]
I still have the bug after upgrade to 11.1.0 (32202) and `docker-machine upgrade dockermachine`.

**Comment by hombit** [comment]
Everything works after restart of VM. Thank you
