### ISSUE TITLE
Parallels docker-machine not working with custom $MACHINE_STORAGE_PATH

### ISSUE THREAD

**Issue by qqalexqq** [Parallels/docker-machine-parallels#17]
When I have $MACHINE_STORAGE_PATH=.machine , e.g. use folder .machine inside current directory, Parallels docker-machine fails to start with an error: `Error creating machine: Error in driver during machine creation: prlctl create prl-dev --distribution boot2docker --dst .machine/machines/prl-dev --no-hdd failed: exit status 1`. The same setting works, for example, with DigitalOcean driver.

**Comment by legal90** [comment]
@qqalexqq Thank you for pointing on this!
Fixed in these releases:
[v1.0.2](https://github.com/Parallels/docker-machine-parallels/releases/tag/v1.0.2) - **only** for Docker Machine 0.5.0
[v1.1.0](https://github.com/Parallels/docker-machine-parallels/releases/tag/v1.1.0) - for Docker Machine 0.5.1+
