### ISSUE TITLE
Driver is incompatible with Docker Machine v0.5.1

### ISSUE THREAD

**Issue by legal90** [Parallels/docker-machine-parallels#18]
In the scope of Docker Machine v0.5.1 release, there were some backward & forward incompatible stuff merged. So, "parallels" driver v1.0.1 could not be used with Docker Machine 0.5.1+
```
$ docker-machine ls
WARNING >>> Error attempting heartbeat call to plugin server: rpc: can't find service RPCServerDriver.Heartbeat
Error attempting to invoke binary for plugin 'parallels': rpc: can't find service RPCServerDriver.GetVersion
```

Docker Machine issue: https://github.com/docker/machine/issues/2325

### Current status for Parallels driver v1.0.*
* It works fine with: Docker Machine [v0.5.0](https://github.com/docker/machine/releases/tag/v0.5.0) / Docker Toolbox [v1.9.0{a..c}](https://github.com/docker/toolbox/releases/tag/v1.9.0c)
* It **doesn't** work with Docker Machine v0.5.1+ / Docker Toolbox v1.9.0d+

_Please, be aware while updating Docker Machine / Docker Toolbox_

### Plans
We have to release a new minor version of Parallels driver (v1.1.0), which will be compatible with Docker Machine v0.5.1 and, unfortunately, incompatible with v0.5.0

**Comment by legal90** [comment]
Unfortunately, there is nothing to fix on our side. I've published two new releases today:
- [v1.0.2](https://github.com/Parallels/docker-machine-parallels/releases/tag/v1.0.2) - **only** for Docker Machine 0.5.0.
- [v1.1.0](https://github.com/Parallels/docker-machine-parallels/releases/tag/v1.1.0) - for Docker Machine 0.5.1+

Next releases will be based on v1.1.0, so we will not support Machine 0.5.0 in the future.

P.s. @kad, please be aware on this if you will decide to update the version in homebrew formulae.

**Comment by kad** [comment]
:) yeah, I'm subscribed to issues and noticed that.
If you don't like to update homebrew formula for your project yourself, I'll update once new releases are done.

**Comment by kad** [comment]
Homebrew updated: Homebrew/homebrew#46227
