### ISSUE TITLE
Error loading driver "parallels": rpc: can't find service RpcServerDriver.GetVersion

### ISSUE THREAD

**Issue by MikeVL** [Parallels/docker-machine-parallels#22]
I can`t create docker vm
➜  ~  docker-machine create --driver=parallels local
WARNING >>> Error attempting heartbeat call to plugin server: rpc: can't find service RpcServerDriver.Heartbeat
Error loading driver "parallels": rpc: can't find service RpcServerDriver.GetVersion

**Comment by legal90** [comment]
It is related to https://github.com/Parallels/docker-machine-parallels/issues/18#issuecomment-158422988

@MikeVL Please, update Docker Machine to v0.5.1. It could be done by installing the latest Docker Toolbox: https://www.docker.com/docker-toolbox

**Comment by remm** [comment]
I've the same issue:
Parallels Desktop Version 11.1.1 (32312) 

➜  ~  docker-machine -v
docker-machine version **0.5.2** ( 0456b9f )

➜  ~  docker-machine create --driver=parallels prl-dev
WARNING >>> Error attempting heartbeat call to plugin server: rpc: can't find service RPCServerDriver.Heartbeat
Error loading driver "parallels": rpc: can't find service RPCServerDriver.GetVersion

**Comment by legal90** [comment]
> Error loading driver "parallels": rpc: can't find service RPCServerDriver.GetVersion
@remm In your case there is a reversed issue. You use the latest Docker Machine, but the outdated plugin version. Please, update the driver plugin:

```
$ curl -L https://github.com/Parallels/docker-machine-parallels/releases/download/v1.1.0/docker-machine-driver-parallels > /usr/local/bin/docker-machine-driver-parallels

$ chmod +x /usr/local/bin/docker-machine-driver-parallels
```

**Comment by remm** [comment]
Yes it works. Thanks.
