### ISSUE TITLE
Add wildcard hostname to /etc/hosts

### ISSUE THREAD

**Issue by MikeVL** [Parallels/docker-machine-parallels#23]
Is it possibly to add `*.docker-machine-name.shared` to `/etc/hosts`?

**Comment by kad** [comment]
wildcards are not allowed in /etc/hosts. neither on MacOS X nor on Linux.

**Comment by legal90** [comment]
@kad is right. It is not possible in `/etc/hosts`, but could be managed by "dnsmask"
http://serverfault.com/questions/118378/in-my-etc-hosts-file-on-linux-osx-how-do-i-do-a-wildcard-subdomain
