### ISSUE TITLE
Cannot lookup registry-1.docker.io... again

### ISSUE THREAD

**Issue by leedm777** [Parallels/docker-machine-parallels#24]
I see that this issue has been filed several times, and is closed as fixed in Parallels 11.1.0. Unfortunately, I recently updated to 11.1.0, and I am still seeing the problem.

Parallels version: 11.1.0 (32202)
docker version: 1.9.1
docker-machine version: 1.5.1
docker-machine-parallels version: 1.1.0

```bash
$ docker pull busybox
Using default tag: latest
Pulling repository docker.io/library/busybox
Get https://registry-1.docker.io/v1/repositories/library/busybox/tags/latest: dial tcp: lookup registry-1.docker.io: no such host
```

I tried the debugging steps mentioned in [#11](https://github.com/Parallels/docker-machine-parallels/issues/11#issuecomment-155365597), but `dig` worked fine in trying to resolve registry-1.docker.io.

**Comment by legal90** [comment]
Have you tried to reload your VM (`docker-machine restart <vm_name>`)?

**Comment by leedm777** [comment]
@legal90 Yes, and I've restarted my Mac, to no effect.

**Comment by rbenedum** [comment]
@leedm777 - I got around this by adding 8.8.8.8 and 8.8.4.4 to my network dns settings

**Comment by leedm777** [comment]
@rbenedum Strangely, it keeps undoing it, so I'm constantly having to go back in and edit `/etc/resolv.conf`.

**Comment by dskr99** [comment]
Hi, I'm a networking developer in parallels, could you please help us to investigate the problem. I've sent an email to you (on yahoo.com mail) with instructions.

**Comment by leedm777** [comment]
Well, now I can't reproduce it. I shall happily continue using docker machine on parallels, and if it happens again, I'll reopen and send the debugging info request.

Thanks!

**Comment by giulianolatini** [comment]
Hi, I've install driver on Parallel 11 for Mac Pro (V. 11.1.3 (32521)) and docker-machine version 0.6.0, build e27fb87. Same problem, same trick to resolve ...but I can't image why. I try to change DNS servers on WiFi configuration and docker don't fire resolve auth.docker.io. Only when I add to /etc/resolv.conf: nameserver 8.8.8.8 docker and docker-compose do work.
