### ISSUE TITLE
support for time-sync

### ISSUE THREAD

**Issue by bassamtabbara** [Parallels/docker-machine-parallels#26]
it doesn't look like docker-machines are created with time-sync enabled. Unfortunately without this the clock skew interferes with normal operations (especially HTTP/S calls). Any chance this can be fixed soon. FWIW enabling it manually fixes the problem.

**Comment by legal90** [comment]
But there is `ntpd` enabled by default in Boot2Docker: https://github.com/boot2docker/boot2docker/blob/eaa536df0f2fac6487dd9c27667111109cb261e3/rootfs/rootfs/etc/rc.d/ntpd
Doesn't it work for you? (check `/var/lib/boot2docker/log/ntpd.log` in the VM)

**Comment by bassamtabbara** [comment]
ntpd is notorious for drifting on VM especially after a long period of sleep/resume

**Comment by legal90** [comment]
@romankulikov What do you think - is it reasonable to enable `--time-sync on --disable-timezone-sync on` in parallel with `ntpd` running in the VM?

**Comment by alexw23** [comment]
:+1:

**Comment by romankulikov** [comment]
@legal90, from my point it is not a good choice to enable both `--time-sync on` and NTP in guest. Clock will go forward and backward constantly. I suggest to use only one of them.

**Comment by legal90** [comment]
@bassamtabbara @alexw23 Can you guys confirm that you don't have any time sync issues after enabling this feature manually for a long time? 

I think about enabling it by default, like in `virtualbox` driver, because this is the only way to fix a time shift after the VM resume.

**Comment by bassamtabbara** [comment]
enabling --time-sync helped us. +1

**Comment by legal90** [comment]
Implemented in [v1.2.0](https://github.com/Parallels/docker-machine-parallels/releases/tag/v1.2.0)
