### ISSUE TITLE
No option to create container in a bridged network

### ISSUE THREAD

**Issue by jahead** [Parallels/docker-machine-parallels#27]
So I've had trouble with trying to follow this guide. 
http://docs.docker.com/engine/userguide/networking/get-started-overlay/

Most of the commands works, but falls over when creating the swarm hosts. Basically the port 3376 is closed due the container being created using a shared interface.  

The docker-machine gets to last stage then reports

```
Setting Docker configuration on the remote daemon...
Error creating machine: Error running provisioning: Unable to verify the Docker daemon is listening: Maximum number of retries (5) exceeded
```

looking further into it, when using `eval $(docker-machine env --swarm mhs-demo0)`  
I get 

```
"10.211.55.6:3376": dial tcp 10.211.55.6:3376: getsockopt: connection refused
```

Which makes sense because there is no port forwarding for this port, but each swarm host 'needs' this port. So manually setting the port forwarding only works for one host, which is pointless. 

Is there an option to create the host with docker-machine's parallel driver specifying the network type and adapter? If not is there any future plans in resolving this issue? As the above case is pretty useful for trying out a swarm deployment before it's deployed onto real servers.

**Comment by legal90** [comment]
@jahead Seems like you've made a mistake. The port of Docker daemon is 2376, not 3376.

And also, while creating the Swarm hosts via `parallels` driver, you should advertise the port on interface `eth0` instead of `eth1`, for example:
```console
$ docker-machine create -d parallels \
    --swarm \
    --swarm-discovery="consul://$(docker-machine ip mh-keystore):8500" \
    --engine-opt="cluster-store=consul://$(docker-machine ip mh-keystore):8500" \
    --engine-opt="cluster-advertise=eth0:2376" \
  mhs-demo0
```

Considering these notes, I've managed to create Swarm cluster from the "Get started guide" (https://docs.docker.com/engine/userguide/networking/get-started-overlay/)  without any issues:
```console
$ docker run -it --rm --net=my-net --env="constraint:node==mhs-demo1" busybox wget -O- http://web

Connecting to web (10.0.0.2:80)
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
...
```
Closed.
