### ISSUE TITLE
Error attempting heartbeat call to plugin server: rpc: can't find method RpcServerDriver.Heartbeat

### ISSUE THREAD

**Issue by mhenrixon** [Parallels/docker-machine-parallels#3]
Not sure why but docker-machine works for other drivers not parallels: https://github.com/docker/machine/issues/2123 is the error I get. It is only a warning but nothing happens. No feedback, no nothing just stops there.

**Comment by legal90** [comment]
Both of our plugin and Docker Machine v0.5.0 are in pre-release state yet, so issues are expected :)

@mhenrixon Please try v1.0.0-rc2 which I've just released: https://github.com/Parallels/docker-machine-parallels/releases/tag/v1.0.0-rc2
It is compatible with Docker Machine v0.5.0-rc4

**Comment by mhenrixon** [comment]
Didn't say I was unaware just that it doesn't work :) How come parallels isn't a default? :(

**Comment by mhenrixon** [comment]
Works like a charm!! Thanks :dancers:

**Comment by legal90** [comment]
> How come parallels isn't a default? :(
Oh, that was a long story... https://github.com/docker/machine/pull/939#issuecomment-126818335

But anyway - in some of the the next Docker Machine releases the most of 3rd party drivers will be split into plugins with their own repositories.

> Works like a charm!! Thanks

Cool! So, I close this issue.
