### ISSUE TITLE
Some errors with docker-machine 5.5

### ISSUE THREAD

**Issue by tomcatzh** [Parallels/docker-machine-parallels#36]
can not run such as ls rm even create

this is the create log:

ZHANGXIAOFENGdeMacBook:.docker zhangxiaofeng$ docker-machine --debug create --driver=parallels --parallels-disk-size=65536 --parallels-memory=4096 --parallels-cpu-count=-1 prl-new
Docker Machine Version:  0.5.5, build 
Found binary path at /usr/local/bin/docker-machine-driver-parallels
Launching plugin server for driver parallels
Plugin server listening at address 127.0.0.1:50308
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetCreateFlags
Found binary path at /usr/local/bin/docker-machine-driver-parallels
Launching plugin server for driver parallels
Plugin server listening at address 127.0.0.1:50312
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(prl-new) Calling .GetMachineName
(prl-new) Calling .DriverName
(prl-new) Calling .GetCreateFlags
(prl-new) Calling .SetConfigFromFlags
Creating CA: /Users/zhangxiaofeng/.docker/machine/certs/ca.pem
Creating client certificate: /Users/zhangxiaofeng/.docker/machine/certs/cert.pem
Running pre-create checks...
(prl-new) Calling .PreCreateCheck
Error creating machine: Error with pre-create check: connection is shut down

**Comment by legal90** [comment]
Duplicates #32
Fixed by #33. The new version will be released in a few hours
