### ISSUE TITLE
mount another folder?

### ISSUE THREAD

**Issue by sumyuga** [Parallels/docker-machine-parallels#4]
Let me know if it's possible to mount not only /Users directory (outside of it). I was trying to change Share settings through Options in Parallels Desktop Control Center and no result at all.

**Comment by legal90** [comment]
@sumyuga It's not convenient, but it's possible.
I guess you did it right, but you also have to mount your custom share on the guest side. All the steps:

1) Add the custom share to the existing VM. It could be done via GUI (in VM settings), or via CLI:
```console
[host]$ prlctl set my-vm-name --shf-host-add my-custom-share --path ~/path-on-the-host
```

2) Start your VM and login there:
```console
[host]$ docker-machine start my-vm-name
[host]$ docker-machine ssh my-vm-name
```

3) Mount custom shared folder folder from the guest side:
```console
[vm]$ sudo mount -t prl_fs  my-custom-share /mnt
```
Done! Let's ensure:
```console
[vm]$ mount | grep prl_fs
Users on /Users type prl_fs (rw,sync,relatime)
my-custom-share on /mnt type prl_fs (rw,sync,relatime)
```

P.s.
You can get the list of available shares by running this in your VM:
```console
[vm]$ cat /proc/fs/prl_fs/sf_list
List of shared folders:
1: Users rw
2: my-custom-share rw
```

**Comment by legal90** [comment]
Unfortunately, you will have to mount it manually after each VM boot. You can try to automate it, using the single command:

```console
[host]$ docker-machine ssh my-vm-name "sudo mkdir -p /mnt/mount_point && sudo mount -t prl_fs  my-custom-share /mnt/mount_point"
```

**Comment by sumyuga** [comment]
Thanks great for this detailed answer!
