### ISSUE TITLE
"unexpected EOF" error when trying to create machine

### ISSUE THREAD

**Issue by mfcollins3** [Parallels/docker-machine-parallels#42]
I upgraded to the latest versions of docker-machine and Parallels Desktop Pro. I also made sure that I have the latest version of the Parallels plugin using Homebrew. When I try to create a machine, it fails with an "unexpected EOF" error. The debug log is below.

Any ideas what I can try to fix this?

Docker Machine Version:  0.6.0, build e27fb87
Found binary path at /usr/local/bin/docker-machine-driver-parallels
Launching plugin server for driver parallels
Plugin server listening at address 127.0.0.1:63500
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetMachineName
(flag-lookup) Calling .DriverName
(flag-lookup) Calling .GetCreateFlags
Found binary path at /usr/local/bin/docker-machine-driver-parallels
Launching plugin server for driver parallels
Plugin server listening at address 127.0.0.1:63504
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(dev) Calling .GetMachineName
(dev) Calling .DriverName
(dev) Calling .GetCreateFlags
(dev) Calling .SetConfigFromFlags
Creating CA: /Users/michaelcollins/.docker/machine/certs/ca.pem
Creating client certificate: /Users/michaelcollins/.docker/machine/certs/cert.pem
Running pre-create checks...
(dev) Calling .PreCreateCheck
(dev) DBG | executing: prlctl --version
(dev) DBG | executing: prlsrvctl info --license
(dev) DBG | Found Parallels Desktop version: 11, edition: pro
(dev) Calling .GetConfigRaw
Creating machine...
(dev) Calling .Create
(dev) Image cache does not exist, creating it at /Users/michaelcollins/.docker/machine/cache...
(dev) No default boot2docker iso found locally, downloading the latest release...
Error creating machine: Error in driver during machine creation: unexpected EOF
open : no such file or directory
notifying bugsnag: [Error creating machine: Error in driver during machine creation: unexpected EOF]

**Comment by mfcollins3** [comment]
Building from source seemed to help. I was having problems with the version that I installed using Homebrew.

**Comment by legal90** [comment]
@mfcollins3  That should be fixed in the latest version of brew formula (docker-machine-parallels 1.1.1_2), by https://github.com/Homebrew/homebrew/pull/50051
Could you please verify it?
```
brew update
brew upgrade docker-machine-parallels
```

**Comment by mfcollins3** [comment]
Sure. I'm at the Microsoft Build conference this week, but I'll verify it tomorrow when I get back.
