### ISSUE TITLE
Suggestion: Use NewDriver instead of new(parallels.Driver) in main.go

### ISSUE THREAD

**Issue by nathanleclaire** [Parallels/docker-machine-parallels#5]
FYI, new(parallels.Driver) will not "migrate" safely if you add new flags (since they will be zero-valued but not over-written), whereas `NewDriver` will.  It's why I changed the drivers in our repo to do so.  Does that make sense?

**Comment by nathanleclaire** [comment]
Nice job being right on top of things btw :)

**Comment by legal90** [comment]
@nathanleclaire Thank you for suggestion! I will do this.
Seems like I should also add `Boot2DockerURL` and `NoShare` to the `NewDriver` function
https://github.com/Parallels/docker-machine-parallels/blob/1be66d340ed3c7c98c33c3ce3cd69285fd9e56af/parallels.go#L56

**Comment by nathanleclaire** [comment]
@legal90 Yeah, totally.  The constructor function is crucial to get those defaults populated on create as well.
