### ISSUE TITLE
prl_fs doesn't support wine: NtMapViewOfSection map_file_into_view

### ISSUE THREAD

**Issue by develar** [Parallels/docker-machine-parallels#52]
I spent two weeks trying to run wine inside docker. But in any case I get error: err:virtual:NtMapViewOfSection map_file_into_view 0x430000 4b52000 000000000 on `wine rcedit.exe <my options>`

Finally I realized that something is broken in the prl_fs — my out folder is mounted to host OS X folder (hint: `noexec` must be not specified — it is not specified, but it is why I realized that it is `prl_fs` issue).

I am Parallels user for years, but for now I have to use trial version of VMware Fusion — it works perfectly. 

If error is not clear for you, I will publish soon my docker images and you can use it to reproduce.

**Comment by legal90** [comment]
@romankulikov, could you please assist here?

**Comment by legal90** [comment]
> If error is not clear for you, I will publish soon my docker images and you can use it to reproduce.
@develar, Yes, that would be great to get a reproduction scenario, so we will be able to investigate the issue.

**Comment by romankulikov** [comment]
I suppose this is another side of the problem #28 with `mmap` support in prl_fs.

**Comment by legal90** [comment]
I'm closing this issue in favor of #28
