### ISSUE TITLE
Exposing ports from docker container?

### ISSUE THREAD

**Issue by citizenmatt** [Parallels/docker-machine-parallels#53]
I'm trying to run a docker container (in a boot2docker Parallels vm) that runs an app that listens on `http://localhost:5000`, but I can't connect to it from my mac. I'm exposing the port in the Dockerfile with `EXPOSE 5000/tcp`, and then running `docker run -p 5000:5000 -t whatever`. But when I hit `localhost:5000` on my mac, it fails to connect.

I suspect I'm missing something obvious - any ideas what's going wrong? Do I need to manually set up port forwarding from my mac's `localhost:5000` to the docker host? And if so, how do I do that?

**Comment by rickard-von-essen** [comment]
`docker run -p 5000:5000 -t whatever` will map port 5000 on you docker-machine vm to port 5000 on the container. It should work if you on your mac connect to `<docker-machine ip>:5000`. You find the ip of your docker machine VM by running `docker-machine ip <name>`.

**Comment by citizenmatt** [comment]
Thanks. I've got it to work, and rather embarrassingly, it was of course, my fault :) I was running a web server that by default only accepted incoming local connections, so hitting `<docker-machine ip>:5000` would fail. Once I configured it correctly, it works great. Thanks for the help, and for the driver too - aside from my mistake, it Just Works.
