### ISSUE TITLE
Mount /Users afrer creation with --parallels-no-share

### ISSUE THREAD

**Issue by dkrotx** [Parallels/docker-machine-parallels#54]
Hi!

I created VM using docker-machine create ... --parallels-no-share. I thought I won't use /Users inside. But then I realized what I need this.

And it seems to be impossible to enable it back via Desktop Control Center: Options/Sharing/Custom Folders /Users has no effect.

**Comment by legal90** [comment]
In this case, you should mount the shared folder manually (in the VM):
```
sudo mkdir /Users
sudo mount -t prl_fs Users /Users
```
[parallels.go#L558-L569](https://github.com/Parallels/docker-machine-parallels/blob/e1964aa5bfade04a6b4db4c7519e4f59257eece5/parallels.go#L558-L569)

**Comment by dkrotx** [comment]
Thanks, works great for me!
