### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pnovotnak** [Parallels/docker-machine-parallels#55]
I don't see a license in this repo. How may I use / reproduce this code?

**Comment by rickard-von-essen** [comment]
@legal90 I'm fine with at least MIT and GPLv2.

**Comment by legal90** [comment]
Yeah, me too. We are just currently discussing it internally at Parallels.

**Comment by legal90** [comment]
Done. Licensed under MIT license: f2cf683af4941001c5034c7f9d7c37138cbb2ee6
