### ISSUE TITLE
allow setting of more (any?) option when creating machines

### ISSUE THREAD

**Issue by globau** [Parallels/docker-machine-parallels#58]
i would like to change the default configuration for a number of options before the vm is started.  (eg. --longer-battery-life off, --isolate-vm on, --device-del usb, --device-del sound0, --device-set hdd0 --online-compact off, ..).  my end goal is to provision a vm tuned for performance over battery usage and disk space.

it would be easier if this were possible to do during the docker-machine creation phase - after it's created but before it is started.  this is because some of the options i want to set require the vm to be stopped, which means the certificates need to be recreated after it's restarted.

perhaps add the ability to pass in a file which is executed immediately before the vm is started in parallels.go::Create() (eg. a json file with params for "prlctl set", or a shell script which is simply executed).

thanks!

**Comment by legal90** [comment]
Hi @globau,
I understand your willings to customize the docker-machine VM on the creation phase, but unfortunately, I can't suggest how to handle this properly on the driver's side. 
The idea about a text file you've mentioned might be working, but it looks very tricky to me and it is too distinct from the general Docker Machine usage scenario. 

This driver was originally created to cover basic use cases which Docker Machine is designed for. I mean the quick bootstrapping a simple tiny VM for running Docker containers for development needs. 

@nathanleclaire What do you think about it? Have you received any similar requests for other Docker Machine drivers?

**Comment by legal90** [comment]
Seems like there are no plans to implement something similar in the Docker Machine mainstream or in other drivers.
Sorry, I'm gonna close this for the reason mentioned in my previous message.

**Comment by globau** [comment]
no worries - thanks for taking the time to investigate it.
