### ISSUE TITLE
Enable Parallels Desktop 10 support

### ISSUE THREAD

**Issue by nunofgs** [Parallels/docker-machine-parallels#6]
Would you be opposed to introducing support for Parallels Desktop 10 and lower (if possible)?

Is there any technical reason why this plugin is limited to Parallels 11?

**Comment by ellomarc** [comment]
+1

**Comment by blueimp** [comment]
I've built a version with support for Parallels Desktop 10 here:
https://github.com/blueimp/docker-machine-parallels/releases/tag/v1.0.0%2Bparallels-10

Here's the pull request for the necessary changes:
https://github.com/Parallels/docker-machine-parallels/pull/10

**Comment by korya** [comment]
+1. If there are some technical limitations, it would be great if I can just specify `-f` flag (or something else) and take the risks and run on "unsupported" version of PD.

**Comment by legal90** [comment]
Closed by #10 
Released in [v1.0.1](https://github.com/Parallels/docker-machine-parallels/releases/tag/v1.0.1)
