### ISSUE TITLE
Can't create a machine

### ISSUE THREAD

**Issue by taoeffect** [Parallels/docker-machine-parallels#66]
So I just dropped $50 to upgrade to Pro so that I could use this driver.

Now I get this:

```
-> % docker-machine create --driver=parallels default
Running pre-create checks...
(default) Image cache directory does not exist, creating it at /Users/greg/.docker/machine/cache...
(default) No default Boot2Docker ISO found locally, downloading the latest release...
(default) Latest release for github.com/boot2docker/boot2docker is v17.05.0-ce
(default) Downloading /Users/greg/.docker/machine/cache/boot2docker.iso from https://github.com/boot2docker/boot2docker/releases/download/v17.05.0-ce/boot2docker.iso...
(default) 0%....10%....20%....30%....40%....50%....60%....70%....80%....90%....100%
Creating machine...
(default) Copying /Users/greg/.docker/machine/cache/boot2docker.iso to /Users/greg/.docker/machine/machines/default/boot2docker.iso...
(default) Creating SSH key...
(default) Creating Parallels Desktop VM...
Error creating machine: Error in driver during machine creation: exit status 255
```

Any help very much appreciated... otherwise I would like my $ back please.

Using `docker-machine` installed via Homebrew, and version:

```
-> % docker-machine --version
docker-machine version 0.11.0, build 5b27455
```

**Comment by taoeffect** [comment]
Forgot to mention, I followed the advice in [this comment](https://github.com/Parallels/docker-machine-parallels/issues/7#issuecomment-153994755) and disabled the Security checkboxes, but still no dice. :-\

![screen shot 2017-05-20 at 2 51 25 pm](https://cloud.githubusercontent.com/assets/138706/26279581/41c428ee-3d6c-11e7-9268-7a5b9c4a8d09.jpg)

**Comment by rickard-von-essen** [comment]
Could you run an paste the output of:

```
/usr/local/bin/prlctl --version
/usr/local/bin/prlctl create default --distribution boot2docker --dst /Users/greg/.docker/machine/machines/default --no-hdd
```

**Comment by taoeffect** [comment]
```
-> % /usr/local/bin/prlctl --version
prlctl version 12.2.0 (41591)
```

I tried several different version of the other (i.e. before running the create command, and after).

Before `create`:

```
-> % /usr/local/bin/prlctl create default --distribution boot2docker --dst ~/.docker/machine/machines/default --no-hdd
Creating the virtual machine...
Generate the VM configuration for boot2docker.
Remove the hdd0 device.
Failed to register the VM: The folder /Users/greg/.docker/machine/machines/default does not exist. Specify another folder and try again.
Failed to create the virtual machine.
```

After:

```
-> % /usr/local/bin/prlctl create default --distribution boot2docker --dst ~/.docker/machine/machines/default --no-hdd
Creating the virtual machine...
Generate the VM configuration for boot2docker.
Remove the hdd0 device.
Failed to register the VM: The operation failed. To perform this operation, you must enter the host OS administrator's credentials.
Failed to create the virtual machine.
```

I tried with `sudo` and it still gave that.

**Comment by legal90** [comment]
> Failed to register the VM: The operation failed. To perform this operation, you must enter the host OS administrator's credentials.

Hm... That error actually means that there are still some password-protected actions. 
Could you please show the output of `prlsrvctl info | grep pass` (without sudo)?

**Comment by taoeffect** [comment]
```
-> % prlsrvctl info | grep pass
Require password to: create-vm add-vm remove-vm clone-vm
Custom password protection: off
```

**Comment by legal90** [comment]
It shows that everything is enabled. Run these commands and then try to run `docker-machine create <...>` again:
```
prlsrvctl set --require-pwd create-vm:off
prlsrvctl set --require-pwd add-vm:off 
prlsrvctl set --require-pwd remove-vm:off
prlsrvctl set --require-pwd clone-vm:off
```

**Comment by taoeffect** [comment]
OK, sorry, I've realized that this is no longer relevant as:

1. It makes much more sense for my use case to use Docker's Mac application, which appears to install different commands than the ones on Homebrew, and also somehow does the virtualization itself in a very lightweight way, without a heavy virtual machine (via Qemu, maybe?)
2. The support people kindly refunded my purchase of the Pro license

So there doesn't seem to be much reason for me to use this or any other virtual driver with Docker, therefore closing.

**Comment by nhooey** [comment]
This issue affects me and I was quite happy using Homebrew's Docker until it stopped working.

**Comment by nhooey** [comment]
In my case, the Parallels Desktop trial had expired. The Parallels driver should mention this.

**Comment by jpowell** [comment]
Same here - no useful error message that Parallels license had expired.
