### ISSUE TITLE
Error checking TLS connection: Host is not running

### ISSUE THREAD

**Issue by titiyoyo** [Parallels/docker-machine-parallels#73]
Every time I create a new docker-machine using the parallels driver I find myself unable to use docker.
I get the message `Error checking TLS connection: Host is not running` and the machine doesn't respond. 

I tried to recreate the machine multiple times with no luck.

It used to work well until a few weeks ago

docker-machine version 0.14.0, build 89b8332
Docker version 18.03.0-ce, build 0520e24
docker-machine-parallels v1.3.0
macOs 10.13.4

**Comment by romankulikov** [comment]
Can you please provide more information describing the problem? What version and edition of Parallels Desktop do you use? When you create docker-machine does virtual machine really start? Can you ssh into this virtual machine?

**Comment by titiyoyo** [comment]
Gladly.
Here they are:

> What version and edition of Parallels Desktop do you use?
Parallels desktop 13 pro edition Version 13.3.0 (43321)

> When you create docker-machine does virtual machine really start?
Yes it starts

> Can you ssh into this virtual machine?
yes

Also I clarify that I'm using docker-compose and not plain docker

**Comment by legal90** [comment]
> Docker version 18.03.0-ce, build 0520e24

@titiyoyo Could you please try to reproduce the error with boot2docker `v18.04.0-ce`, which was released recently? Just create a new docker machine vm from a scratch, so it will use the latest stable release of boot2docker.

I just think that your issue could have the same root cause as this one (was fixed in boot2docker `v18.04.0-ce-rc1` ): https://github.com/Parallels/docker-machine-parallels/issues/72#issuecomment-368339936

**Comment by titiyoyo** [comment]
@legal90 the same thing happens with a new machine using v18.04.0-ce

**Comment by titiyoyo** [comment]
I removed ~/.docker folder and then re created my machine and now the error's gone, apparently there was something wrong there. I'll try to restore a previous snapshot and investigate what was going wrong a little further

**Comment by titiyoyo** [comment]
I restored my other (and previously non functioning) machine, and now it works, using it's old certs.
I don't know what could have caused the problem, maybe a permission problem on one of the `.docker` subdirectories

**Comment by abdennour** [comment]
```
docker-machine regenerate-certs default
```
Or if you have a docker-machine with custom name (i.e: `mymachine`)

```
docker-machine regenerate-certs mymachine

```

And so on.
