### ISSUE TITLE
files are bind-mounted as directories

### ISSUE THREAD

**Issue by tagirb** [Parallels/docker-machine-parallels#75]
If I bind-mounting a file to a container, inside of the container I see a directory instead of that file:
```
~$ docker run -it --rm -v $HOME/.bash_history:/.bash_history alpine:latest /bin/sh
/ # ls -ld /.bash_history
drwxr-xr-x    2 root     root            40 Apr 25 07:30 /.bash_history
/ # %
```

My assumption is that Parallels Shared Folder doesn't support this. Can you confirm it?

**Comment by romankulikov** [comment]
Confirm. Functionality of Shared Folders in Parallels Desktop doesn't support sharing regular files, only directories.

**Comment by tagirb** [comment]
Thanks Roman!

What is your feeling about the project in general? Based on the project activity, my impression is it is not really actively used and supported.

**Comment by romankulikov** [comment]
Well. I might agree that docker-machine-parallels is not under the major focus of Parallels Desktop product. But anyway there's some (micro)user-base of it. And we try to fix vital issues.
