### ISSUE TITLE
Folders not shared

### ISSUE THREAD

**Issue by ronn0** [Parallels/docker-machine-parallels#76]
When i start my Parallels container the folders aren't shared (or mounted)

![schermafbeelding 2018-09-24 om 12 56 51](https://user-images.githubusercontent.com/14876955/45948703-59411700-bff9-11e8-9ac8-7450ff5299d8.png)

There is no folder /Users/etc/etc

![schermafbeelding 2018-09-24 om 12 57 45](https://user-images.githubusercontent.com/14876955/45948744-7bd33000-bff9-11e8-86d8-3f3756cc5143.png)

**Comment by romankulikov** [comment]
In the guest (prl-dev virtual machine) Shared Folders are mounted inside `/media/psf`. Check them out:
```
# mout | fgrep /media/psf
```

**Comment by legal90** [comment]
Hi @ronn0,
Looking at the first screenshot I can say that your shared folder settings look misconfigured. `"Home folder only"` should not be selected there. Luckily, it's easy to fix. Just run this on your Mac host:
```
prlctl set prl-dev --shf-host-defined off
prlctl set prl-dev --shf-host-add Users --path /Users
```
And then restart the VM:
```
docker-machine restart prl-dev
```
After that you should see the shared folder mounted to the VM:
```
$ docker-machine ssh prl-dev -- ls /Users
Guest
Shared
legal
```

**Comment by legal90** [comment]
Note that `/Users` path is hardcoded in our driver, so you can't mount other folders by default. Here we just follow the behavior of other drivers in upstream, such as `vmwarefusion` and `virualbox`.

**Comment by ronn0** [comment]
This did the trick. Thanks for that.
