### ISSUE TITLE
Cool kids say homebrew

### ISSUE THREAD

**Issue by ianbytchek** [Parallels/docker-machine-parallels#8]
So I've heard… :smile: can we have a formula for the plugin?

**Comment by krasilich** [comment]
Hi Ian, could you please provide little bit more details on your issue, because it's not quite cleare how to help you)

**Comment by Dahlgren** [comment]
It's available through homebrew already, https://github.com/Homebrew/homebrew/commit/112ccbdc6e1db1826328102980f253e8d2067112

**Comment by ianbytchek** [comment]
@Dahlgren will work on my `brew search` skills. Thanks!
