### ISSUE TITLE
Hosts are not updated with Parallels Desktop 15

### ISSUE THREAD

**Issue by ianbytchek** [Parallels/docker-machine-parallels#82]
Upgraded to Parallels Desktop 15 over a week ago and everything worked smooth until this morning – all services relying on the local hostname added by the Parallels provider to /etc/hosts stopped working complaining the host couldn't be found. After a few macOS restarts and unsuccessful recovery attempts I reverted back to version 14 and /etc/hosts began updating as usual.

With version 15 behaving okay for 1+ week this can be a local glitch but it's suspicious that everything went back to normal immediately after reverting to version 14. Flagging this up just in case.

**Comment by romankulikov** [comment]
I'm I right saying that VMs' host names were not added to `/etc/hosts` of your macOS?

**Comment by ianbytchek** [comment]
Yes, correct – `/etc/hosts` on the host macOS (10.14.6 (18G103)) are not updated. AFAIK this is handled by the Parallels provider, not docker-machine – checking in case I got this mixed up.

**Comment by romankulikov** [comment]
Can you please generate a technical report when this issue is reproducing and post report's id here?

**Comment by ryansch** [comment]
I've run into this behaviour on both 14 and 15 a handful of times over the past year. I'll post a report the next time I run into it.

**Comment by ianbytchek** [comment]
I haven't seen this issue for awhile now. Feel free to reopen if there's any other info.
