### ISSUE TITLE
MacOS Catalina 10.15.4 with supplement update: Cannot create VM "Your Mac host is not connected to Shared network"

### ISSUE THREAD

**Issue by pozgo** [Parallels/docker-machine-parallels#87]
After updating to MacOS 10.15.4 (19E287_) Supplemental Update today cannot create docker machine anymore using parallels

```
docker-machine create --driver=parallels --parallels-memory=4096 --parallels-cpu-count=2 docker

Running pre-create checks...
Error with pre-create check: "Your Mac host is not connected to Shared network. Please, enable this option: 'Parallels Desktop' -> 'Preferences' -> 'Network' -> 'Shared' -> 'Connect Mac to this network'"
```
Yet the Parallels is working correctly

![Screenshot 2020-04-16 at 21 50 02](https://user-images.githubusercontent.com/1773188/79505411-3edfeb80-802c-11ea-9db7-2184a562032d.png)

**Comment by romankulikov** [comment]
Can you please provide output of command `prlsrvctl net info Shared`?

**Comment by pozgo** [comment]
```
prlsrvctl net info Shared
Network ID: Shared
Type: shared
Parallels adapter:
        IPv4 address: 10.211.55.2
        IPv4 subnet mask: 255.255.255.0
        Host assign IP v6: off
        IPv6 address: fdb2:2c26:f4e4::
        IPv6 subnet mask: ffff:ffff:ffff:ffff::
DHCPv4 server:
        Server address: 10.211.55.1
        IP scope start address: 10.211.55.1
        IP scope end address: 10.211.55.254
DHCPv6 server:
        Server address: fdb2:2c26:f4e4::1
        IP scope start address: fdb2:2c26:f4e4::
        IP scope end address: fdb2:2c26:f4e4:0:ffff:ffff:ffff:ffff

NAT server:
```

**Comment by pozgo** [comment]
I think the issue related to parallels itself rather than this module.
After reboot, all works as expected. Until one reboot it doesn't due to obviously not loading the driver.

**Comment by legal90** [comment]
The last output you've posted does not contain the line `Bound To: vnic0`, which leaded to the error you got.
So, yes - usually, the reboot helps to solve it 👍
