### ISSUE TITLE
Can't start minikube: HostIP not yet implemented for "parallels" driver

### ISSUE THREAD

**Issue by antoniogermano** [Parallels/docker-machine-parallels#90]
Minikube works with HyperKit and also VirtualBox, but does not work with the Parallels driver.
The issue is `HostIP not yet implemented for "parallels" driver`

I have installed the parallels driver with MacPorts, and then uninstalled that and installed with Homebrew, but it didn't make a difference, I get the same error message on either.

Here's the complete log:
```
Server:~ antoniogermano$ minikube start
😄  minikube v1.10.1 on Darwin 10.15.4
✨  Using the parallels driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating parallels VM (CPUs=2, Memory=3072MB, Disk=20000MB) ...
❗  This VM is having trouble accessing https://k8s.gcr.io
💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
🐳  Preparing Kubernetes v1.18.2 on Docker 19.03.8 ...
E0520 09:36:19.132217   60998 start.go:95] Unable to get host IP: HostIP not yet implemented for "parallels" driver

💣  failed to start node: startup failed: Failed to setup kubeconfig: HostIP not yet implemented for "parallels" driver

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose
```

I know the log asks to open the issue on the minikube project, but I've got the feeling that if I do, they will ask me to open an issue here.

Thank you in advance!

**Comment by legal90** [comment]
Hi @antoniogermano,

`libmachine` doesn't provide a way to expose HostIP, so it seems it should be implemented on the minikube side. The error comes from here:
https://github.com/kubernetes/minikube/blob/522c746df4b653d4a77f98be737025bf23d10a5b/pkg/minikube/cluster/ip.go#L90

And there is an ongoing discussion about Parallels support for minikube:
https://github.com/kubernetes/minikube/issues/4862

I think it should be pretty easy to do. I'll check if I can implement it and contribute there soon.

**Comment by legal90** [comment]
I sent the PR to the minikube repo: https://github.com/kubernetes/minikube/pull/8259

**Comment by legal90** [comment]
kubernetes/minikube#8259 was merged
