### ISSUE TITLE
Error with pre-create check: "Parallels Desktop edition could not be fetched!"

### ISSUE THREAD

**Issue by tstromberg** [Parallels/docker-machine-parallels#91]
This happens with both docker-machine and minikube:

```
%  docker-machine create --driver=parallels prl-dev                                                                                                                                                                                              Creating CA: /Users/tstromberg/.docker/machine/certs/ca.pem
Creating client certificate: /Users/tstromberg/.docker/machine/certs/cert.pem
Running pre-create checks...
Error with pre-create check: "Parallels Desktop edition could not be fetched!"
```

Looking at the code - the parsing appears to be made here:

https://github.com/Parallels/docker-machine-parallels/blob/ae235d0689e70542f27c6a327596983389579485/parallels_darwin.go#L783

Here is what I believe the underlying command output is:

```
% prlsrvctl info --license
Searching for installed licenses...
No licenses installed.
```

I just downloaded a demo of Parallels to help a minikube user out, so I do not have a license. May I suggest that, if a license is required, that the error message be updated to show something like:

`docker-machine-parallels requires a Parallels license to be purchased: https://www.parallels.com/`

Alternatively, if this is just the case of a regular expression changing, I thought you should know.

**Comment by tstromberg** [comment]
The appropriate workaround I found was to select `Account & License...` in the `Parallels` menu. Add a user, and select a 14-day trial. Then a license showed up and docker-machine + minikube could run as expected.

**Comment by legal90** [comment]
@tstromberg Thank you for pointing on this! I agree - we should update the error message and make it more helpful 👍
