### ISSUE TITLE
Should an deprecated-info added since docker-machine is only in maintenance mode anymore

### ISSUE THREAD

**Issue by josefglatz** [Parallels/docker-machine-parallels#92]

**Comment by legal90** [comment]
Hi @josefglatz,

Despite the fact that Docker Machine itself is in the maintenance mode, it was not actually deprecated (https://github.com/docker/machine/issues/4537).
It could still be used. And, what's more important, `libmachine` library is not deprecated neither.

Our driver, which we traditionally call "docker machine driver" could also be used with other projects leveraging drivers based on libmachine. For example, with minikube:
- https://minikube.sigs.k8s.io/docs/
- https://minikube.sigs.k8s.io/docs/drivers/parallels/
It's a popular tool and it doesn't directly depend nor on docker-machine, neither on boot2docker. 

So, I think we should not deprecate our driver now. 
Though, it makes sense to update or main README.md and project description to point that it could be also used with minikube (like it's done in https://github.com/machine-drivers/docker-machine-driver-xhyve).
