### ISSUE TITLE
parallels license for testing minikube

### ISSUE THREAD

**Issue by medyagh** [Parallels/docker-machine-parallels#97]
apologizes if this is the wrong place to ask, but  I am one of the [minikube](https://minikube.sigs.k8s.io/) maintainers, we test minikube against many virtualization technologies (hyperv, vbox, hyperkit,...) but in  we have un-tested support for parallel driver, if parallels team is interested we could test minikube against parallels too.

**Comment by legal90** [comment]
@andreydanin ^ Do you have any insides from Parallels regarding this?  
`minikube` uses our driver in a similar way as Docker Machine does it. 
And the user base of `minikube` is growing fast, unlike the Docker Machine, which is in "maintenance mode" (aka deprecated).

**Comment by andreydanin** [comment]
Hi @medyagh. What do you expect from the Parallels team? What actions will be required from our side?
