### ISSUE TITLE
Docker Machine doesn't detect files changed event

### ISSUE THREAD

**Issue by Uhucream** [Parallels/docker-machine-parallels#98]
I use Docker Machine driver with Parallels Desktop, and I want to use `yarn run watch` inside docker, but docker-compose with Docker Machine doesn't detect any files changed event. So `yarn run watch` is supposed to build react application when files changed, but docker-compose with docker machine doesn't.

I don't know what is cause.
Please tell me that.

**Comment by vitalik74** [comment]
+1 The same issue. Using webpack-dev-server

**Comment by legal90** [comment]
@Uhucream @vitalik74 , could you please post the details of your environment?
- version of macOS version
- version of Parallels Desktop for Mac
- version of boot2docker used in your docker-machine VM.

Also, it would be good to have a reproduction scenario

**Comment by vitalik74** [comment]
@legal90 Michael, hey,
Thanks for reply!

I found the solution. Need add `--watch-poll` in run command. Or set 
```
watchOptions: {
   poll: true
}
```

In `webpack.cpnfig.js`

See the doc: 
https://webpack.js.org/guides/development-vagrant/#running-the-server
https://webpack.js.org/configuration/watch/#watchoptionspoll

**Comment by Uhucream** [comment]
@legal90 

> @Uhucream @vitalik74 , could you please post the details of your environment?
> 
> - version of macOS version
> 
> - version of Parallels Desktop for Mac
> 
> - version of boot2docker used in your docker-machine VM.
> 
> 
> 
> Also, it would be good to have a reproduction scenario

Thank you for responding and I'm sorry not to respond quickly and sorry not to provide enough information.

My environment is below.
- macOS: Big Sur(It was Catalina when I had posted this issue.)

- Parallels Desktop: 16
- boot2docker: 19.03.12

**Comment by Uhucream** [comment]
@vitalik74 
> @legal90 Michael, hey,
> Thanks for reply!
> 
> I found the solution. Need add `--watch-poll` in run command.
> 
> ```
> yarn webpack-dev-server  --host 0.0.0.0 --public site.local --progress --watch-poll
> ```
> 
> Or set
> 
> ```
> watchOptions: {
>    poll: true
> }
> ```
> 
> In `webpack.config.js`
> 
> See the doc:
> https://webpack.js.org/guides/development-vagrant/#running-the-server
> https://webpack.js.org/configuration/watch/#watchoptionspoll
> 
> And this is the webpack problem:
> `If watching does not work for you, try out this option. Watching does not work with NFS and machines in VirtualBox.`
> 
> Otherwise it can spend some CPU and disk. You can sen poll = 1000 (1 sec) if this option downs your system

I've tried it, then it works!
Thanks!
